apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: 11124githubjenkinsgo 
  janus-idp.io/tekton: 11124githubjenkinsgo
  backstage.io/kubernetes-id: 11124githubjenkinsgo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 11124githubjenkinsgo
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  