apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: 11124githubjenkinsgo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 11124githubjenkinsgo 
  name: 11124githubjenkinsgo
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 11124githubjenkinsgo
    weight: 100 
